### ISSUE TITLE
AttributeError: 'Backup' object has no attribute 'archive_dir'

### ISSUE THREAD

**Issue by ShahriyarR** [Shelnutt2/MySQL-AutoXtraBackup#6]
Hi :)
Can't wait and tried your repo :P

With following bck.cnf:

```
[MySQL]
mysql=/home/sh/MySQLPakcages/mysql-5.6.32/5.6.32/bin/mysql
mycnf=/home/sh/sandboxes/msb_5_6_32/my.sandbox.cnf
mysqladmin=/home/sh/MySQLPakcages/mysql-5.6.32/5.6.32/bin/mysqladmin
mysql_user=msandbox
mysql_password=msandbox
#Set either mysql_socket or host and post. If both are set socket is used
#mysql_socket=/var/lib/mysql/mysql.sock
mysql_host=127.0.0.1
mysql_port=5632
xtra_prepare=--apply-log --redo-only
datadir=/home/sh/sandboxes/msb_5_6_32/data/
tmpdir=/tmp/mysql
tmp=/tmp


[Backup]
#Optional: set pid directory
#pid_dir=/var/run/MySQL-AutoXtraBackup
#Optional: set warning if pid of backup us running for longer than X
pid_runtime_warning=2 Hours
backupdir=/home/backup_dir
backup_tool=/usr/bin/innobackupex
#Optional: set archive and rotation
#archive_dir=/home/backup_archives
full_backup_interval=1 day
#max_archive_size=100GiB
#max_archive_duration=4 Days

#Optional remote syncing
#[Remote]
#remote_conn=root@xxx.xxx.xxx.xxx
#remote_dir=/home/sh/Documents


[Commands]
start_mysql_command=service mysql start
stop_mysql_command=service mysql stop
systemd_start_mysql=systemctl start mysqld.service
systemd_stop_mysql=systemctl stop mysqld.service
systemd_start_mariadb=systemctl start mariadb.service
systemd_stop_mariadb=systemctl stop mariadb.service
mkdir_command=mkdir /var/lib/mysql
chown_command=chown -R mysql:mysql /var/lib/mysql
mariadb_cluster_bootstrap=service mysql bootstrap
```

The result is:

```
sh@sh-ubuntu:~/REPOS/MySQL-AutoXtraBackup$ autoxtrabackup --backup
Warning: Using a password on the command line interface can be insecure.
Traceback (most recent call last):
  File "/usr/local/bin/autoxtrabackup", line 9, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.0', 'console_scripts', 'autoxtrabackup')()
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mysql_autoxtrabackup-1.4.0-py3.5.egg/autoxtrabackup.py", line 68, in all_procedure
  File "/usr/local/lib/python3.5/dist-packages/mysql_autoxtrabackup-1.4.0-py3.5.egg/master_backup_script/backuper.py", line 345, in all_backup
  File "/usr/local/lib/python3.5/dist-packages/mysql_autoxtrabackup-1.4.0-py3.5.egg/master_backup_script/check_env.py", line 402, in check_all_env
  File "/usr/local/lib/python3.5/dist-packages/mysql_autoxtrabackup-1.4.0-py3.5.egg/master_backup_script/check_env.py", line 111, in check_mysql_archive_dir
AttributeError: 'Backup' object has no attribute 'archive_dir'
```

**Comment by ShahriyarR** [comment]
Another check failed on:
```
            elif self.last_full_backup_date() == 1:
                logger.debug("################################################################")
                logger.debug("Your full backup is timeout : Taking new Full Backup!- - - - - #")
                logger.debug("################################################################")

                time.sleep(3)

                # Archiving backups
       # =>      if self.archive_dir:     # <=
                    if (hasattr(self, 'max_archive_duration') and self.max_archive_duration) or (
                                hasattr(self, 'max_archive_size') and self.max_archive_size):
```

The result:

```
sh@sh-ubuntu:~/REPOS/MySQL-AutoXtraBackup$ autoxtrabackup --backup
Warning: Using a password on the command line interface can be insecure.
Traceback (most recent call last):
  File "/usr/local/bin/autoxtrabackup", line 9, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.1', 'console_scripts', 'autoxtrabackup')()
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mysql_autoxtrabackup-1.4.1-py3.5.egg/autoxtrabackup.py", line 68, in all_procedure
  File "/usr/local/lib/python3.5/dist-packages/mysql_autoxtrabackup-1.4.1-py3.5.egg/master_backup_script/backuper.py", line 377, in all_backup
AttributeError: 'Backup' object has no attribute 'archive_dir'
```
